name = "Unstruct LLMWhisperer"
description = "LLMWhisperer is a technology that presents data from complex documents (different designs and formats) to LLMs in a way that they can best understand."
currency = "USD"
url = "https://unstract.com/"
github = ""
docs = "https://docs.unstract.com/llmwhisperer/index.html"
type = "Cloud"
last_updated = "2025-09-16"

[metadata]
default_billing_frequency = "Monthly"
default_currency = "USD"
has_usage_based_billing = true
has_enterprise_option = true
has_free_tier = true
free_tier = "100 pages/day"

has_trial = false

eu_hosting = "Available"
# can be hosted in EU datacenter

[compliance]
gdpr = true
soc_two = true
iso = true
# ISO 27001
hipaa = true

[processing]
tables = true
forms = true
images = true
graphs = true
equation = true
ocr = true

[input_formats]
pdf = true
spreadsheet = true
word = true
powerpoint = true
html = true
epub = false
images = true

[output_formats]
json = true
markdown = true
html = false
plain = false
structuredData = false


[[tiers]]
name = "Pay as you go"
billing_type = "pay-as-you-go"
price = "$1-15 /1000 pages"
# NATIVE TEXT $1/1000 pages
# LOW COST $5/1000 pages for high quality scans
# HIGH QUALITY $10/1000 pages
# HIGH QUALITY with forms $15/1000 pages
included_quota = "100 pages/month"
billing_frequency = "Monthly"
currency = "USD"
cost_per_unit = "$0.01/page"
features = [
    "API or UI access for document processing",
    "Access to latest VLMs for partitioning and enrichment",
    "Balance speed, performance and cost with different partition strategies",
    "Transform 80+ file types",
    "HIPAA, SOC2 Type 2, GDPR and ISO 27001 compliance",
    "Basic support"
]

[[tiers]]
name = "Enterprise"
price = "Custom"
billing_type = "Subscription"
billing_frequency = "Monthly"
included_quota = ""
currency = "USD"
cost_per_unit = ""
features = [
    "Customer-hosted deployment"
]
