name = "Chunkr"
description = "Chunkr AI is an API service to convert complex documents into LLM/RAG-ready data."
currency = "USD"
url = "https://www.chunkr.ai/"
github = "https://github.com/lumina-ai-inc/chunkr"
docs = "https://docs.chunkr.ai/docs/get-started/overview"
type = ["Cloud", "Self-hosted"]
last_updated = "2025-10-02"

[metadata]
default_billing_frequency = "Monthly"
default_currency = "USD"
has_usage_based_billing = true
has_enterprise_option = true
has_free_tier = true

credits = "1 PDF page = 1 credit. Pages with VLM processing are billed at 2 credits per page. 5,000 spreadsheet cells = 1 credit (rounded up)."



[compliance]
gdpr = ""
soc_two = ""
iso = ""


[input_formats]
pdf = true
spreadsheet = true
word = true
powerpoint = true
html = false
epub = false
images = false

[output_formats]
json = true
markdown = true
html = true
plain = false
structuredData = true


[[tiers]]
name = "Free"
billing_type = "Usage"
price = "$0/month"
included_quota = "200 pages"
billing_frequency = "Monthly"
currency = "USD"
cost_per_unit = ""
features = [
    "No payment info required",
    "Discord community support"
]

[[tiers]]
name = "Dev"
price = "$375/month"
billing_type = "Subscription, Usage"
billing_frequency = "Monthly"
included_quota = "25,000 credits"
currency = "USD"
cost_per_unit = "$0.015 / credit (page)"
features = [
    "Priority support channel"
]

[[tiers]]
name = "Growth"
price = "$750/month"
billing_type = "Subscription, Usage"
billing_frequency = "Monthly"
included_quota = "75,000 credits"
currency = "USD"
cost_per_unit = "$0.010 / credit (page)"
features = [
    "Dedicated founder support"
]

[[tiers]]
name = "Scale"
price = "$2000/month"
billing_type = "Subscription, Usage"
billing_frequency = "Monthly"
included_quota = "250,000 credits"
currency = "USD"
cost_per_unit = "$0.008 / credit (page)"
features = [
    "Dedicated founder support"
]
